# Generated by Django 4.2.3 on 2023-09-03 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='dev-case.com', max_length=255)),
                ('favicon', models.ImageField(upload_to='')),
                ('copyright_footer', models.CharField(default='Your Name © 2022', max_length=255)),
                ('email_adresse', models.CharField(default='email [@] adress [dot] com', max_length=255)),
            ],
            options={
                'verbose_name': 'Main Settings',
            },
        ),
        migrations.CreateModel(
            name='SocialAccountsConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('gitlab', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('instagram', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('linkedin', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('mastodon', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('twitter', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('xing', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('youtube', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('rss', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Social Accounts',
            },
        ),
    ]
